sudo: required

dist: bionic

language: node_js

node_js:
  - 12

python:
  - "3.7"

services:
  - docker
  - xvfb

install:
  - npm install

script:
  - bash ./deploy.sh sartography/cr-connect-angular-base

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - dan@sartography.com
